GET http://localhost:8000/v1/emailList

###

POST  http://localhost:8000/v1/emailList/createEmailList 
Content-Type: application/json

{
    "fName": "test4",
    "email": "tempzaq1234@gmail.com",
    "groupId": "5"
}

###

GET http://localhost:8000/v1/emailList/sendNewEmail

